### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ygumattos** [ygumattos/english-class-telegram-bot#2]
- [x] Conectar com Telegram Bot
- [x] Capturar audio
- [x] Refatoração
- [x] Salvar id em uma lista
- [x] Ao enviar audio, perguntar se quer substituir o anterior
- [x] Comando para adicionar aluno
- [x] Comando para escolher alunos
- [x] Comando para enviar audio para aluno 
- [x] Enviar Audio
- [x] Listar comandos
- [ ] Refatoração
